// Copyright 2024 Authors of infrastructure-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/apis/topohub.infrastructure.io/v1beta1"
	topohubinfrastructureiov1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/client/clientset/versioned/typed/topohub.infrastructure.io/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSubnets implements SubnetInterface
type fakeSubnets struct {
	*gentype.FakeClientWithList[*v1beta1.Subnet, *v1beta1.SubnetList]
	Fake *FakeTopohubV1beta1
}

func newFakeSubnets(fake *FakeTopohubV1beta1) topohubinfrastructureiov1beta1.SubnetInterface {
	return &fakeSubnets{
		gentype.NewFakeClientWithList[*v1beta1.Subnet, *v1beta1.SubnetList](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("subnets"),
			v1beta1.SchemeGroupVersion.WithKind("Subnet"),
			func() *v1beta1.Subnet { return &v1beta1.Subnet{} },
			func() *v1beta1.SubnetList { return &v1beta1.SubnetList{} },
			func(dst, src *v1beta1.SubnetList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.SubnetList) []*v1beta1.Subnet { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta1.SubnetList, items []*v1beta1.Subnet) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
