// Copyright 2024 Authors of infrastructure-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/apis/topohub.infrastructure.io/v1beta1"
	topohubinfrastructureiov1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/client/clientset/versioned/typed/topohub.infrastructure.io/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeRedfishStatuses implements RedfishStatusInterface
type fakeRedfishStatuses struct {
	*gentype.FakeClientWithList[*v1beta1.RedfishStatus, *v1beta1.RedfishStatusList]
	Fake *FakeTopohubV1beta1
}

func newFakeRedfishStatuses(fake *FakeTopohubV1beta1) topohubinfrastructureiov1beta1.RedfishStatusInterface {
	return &fakeRedfishStatuses{
		gentype.NewFakeClientWithList[*v1beta1.RedfishStatus, *v1beta1.RedfishStatusList](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("redfishstatuses"),
			v1beta1.SchemeGroupVersion.WithKind("RedfishStatus"),
			func() *v1beta1.RedfishStatus { return &v1beta1.RedfishStatus{} },
			func() *v1beta1.RedfishStatusList { return &v1beta1.RedfishStatusList{} },
			func(dst, src *v1beta1.RedfishStatusList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.RedfishStatusList) []*v1beta1.RedfishStatus {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.RedfishStatusList, items []*v1beta1.RedfishStatus) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
