// Copyright 2024 Authors of infrastructure-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/apis/topohub.infrastructure.io/v1beta1"
	topohubinfrastructureiov1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/client/clientset/versioned/typed/topohub.infrastructure.io/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeHostOperations implements HostOperationInterface
type fakeHostOperations struct {
	*gentype.FakeClientWithList[*v1beta1.HostOperation, *v1beta1.HostOperationList]
	Fake *FakeTopohubV1beta1
}

func newFakeHostOperations(fake *FakeTopohubV1beta1) topohubinfrastructureiov1beta1.HostOperationInterface {
	return &fakeHostOperations{
		gentype.NewFakeClientWithList[*v1beta1.HostOperation, *v1beta1.HostOperationList](
			fake.Fake,
			"",
			v1beta1.SchemeGroupVersion.WithResource("hostoperations"),
			v1beta1.SchemeGroupVersion.WithKind("HostOperation"),
			func() *v1beta1.HostOperation { return &v1beta1.HostOperation{} },
			func() *v1beta1.HostOperationList { return &v1beta1.HostOperationList{} },
			func(dst, src *v1beta1.HostOperationList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.HostOperationList) []*v1beta1.HostOperation {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.HostOperationList, items []*v1beta1.HostOperation) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
