// Copyright 2024 Authors of infrastructure-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	topohubinfrastructureiov1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/apis/topohub.infrastructure.io/v1beta1"
	scheme "github.com/infrastructure-io/topohub/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BindingIpsGetter has a method to return a BindingIpInterface.
// A group's client should implement this interface.
type BindingIpsGetter interface {
	BindingIps() BindingIpInterface
}

// BindingIpInterface has methods to work with BindingIp resources.
type BindingIpInterface interface {
	Create(ctx context.Context, bindingIp *topohubinfrastructureiov1beta1.BindingIp, opts v1.CreateOptions) (*topohubinfrastructureiov1beta1.BindingIp, error)
	Update(ctx context.Context, bindingIp *topohubinfrastructureiov1beta1.BindingIp, opts v1.UpdateOptions) (*topohubinfrastructureiov1beta1.BindingIp, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, bindingIp *topohubinfrastructureiov1beta1.BindingIp, opts v1.UpdateOptions) (*topohubinfrastructureiov1beta1.BindingIp, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*topohubinfrastructureiov1beta1.BindingIp, error)
	List(ctx context.Context, opts v1.ListOptions) (*topohubinfrastructureiov1beta1.BindingIpList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *topohubinfrastructureiov1beta1.BindingIp, err error)
	BindingIpExpansion
}

// bindingIps implements BindingIpInterface
type bindingIps struct {
	*gentype.ClientWithList[*topohubinfrastructureiov1beta1.BindingIp, *topohubinfrastructureiov1beta1.BindingIpList]
}

// newBindingIps returns a BindingIps
func newBindingIps(c *TopohubV1beta1Client) *bindingIps {
	return &bindingIps{
		gentype.NewClientWithList[*topohubinfrastructureiov1beta1.BindingIp, *topohubinfrastructureiov1beta1.BindingIpList](
			"bindingips",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *topohubinfrastructureiov1beta1.BindingIp { return &topohubinfrastructureiov1beta1.BindingIp{} },
			func() *topohubinfrastructureiov1beta1.BindingIpList {
				return &topohubinfrastructureiov1beta1.BindingIpList{}
			},
		),
	}
}
