// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	topohubinfrastructureiov1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/apis/topohub.infrastructure.io/v1beta1"
	scheme "github.com/infrastructure-io/topohub/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterAgentsGetter has a method to return a ClusterAgentInterface.
// A group's client should implement this interface.
type ClusterAgentsGetter interface {
	ClusterAgents() ClusterAgentInterface
}

// ClusterAgentInterface has methods to work with ClusterAgent resources.
type ClusterAgentInterface interface {
	Create(ctx context.Context, clusterAgent *topohubinfrastructureiov1beta1.ClusterAgent, opts v1.CreateOptions) (*topohubinfrastructureiov1beta1.ClusterAgent, error)
	Update(ctx context.Context, clusterAgent *topohubinfrastructureiov1beta1.ClusterAgent, opts v1.UpdateOptions) (*topohubinfrastructureiov1beta1.ClusterAgent, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterAgent *topohubinfrastructureiov1beta1.ClusterAgent, opts v1.UpdateOptions) (*topohubinfrastructureiov1beta1.ClusterAgent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*topohubinfrastructureiov1beta1.ClusterAgent, error)
	List(ctx context.Context, opts v1.ListOptions) (*topohubinfrastructureiov1beta1.ClusterAgentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *topohubinfrastructureiov1beta1.ClusterAgent, err error)
	ClusterAgentExpansion
}

// clusterAgents implements ClusterAgentInterface
type clusterAgents struct {
	*gentype.ClientWithList[*topohubinfrastructureiov1beta1.ClusterAgent, *topohubinfrastructureiov1beta1.ClusterAgentList]
}

// newClusterAgents returns a ClusterAgents
func newClusterAgents(c *TopohubV1beta1Client) *clusterAgents {
	return &clusterAgents{
		gentype.NewClientWithList[*topohubinfrastructureiov1beta1.ClusterAgent, *topohubinfrastructureiov1beta1.ClusterAgentList](
			"clusteragents",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *topohubinfrastructureiov1beta1.ClusterAgent {
				return &topohubinfrastructureiov1beta1.ClusterAgent{}
			},
			func() *topohubinfrastructureiov1beta1.ClusterAgentList {
				return &topohubinfrastructureiov1beta1.ClusterAgentList{}
			},
		),
	}
}
