// Copyright 2024 Authors of elf-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	topohubinfrastructureiov1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/apis/topohub.infrastructure.io/v1beta1"
	scheme "github.com/infrastructure-io/topohub/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// HostOperationsGetter has a method to return a HostOperationInterface.
// A group's client should implement this interface.
type HostOperationsGetter interface {
	HostOperations() HostOperationInterface
}

// HostOperationInterface has methods to work with HostOperation resources.
type HostOperationInterface interface {
	Create(ctx context.Context, hostOperation *topohubinfrastructureiov1beta1.HostOperation, opts v1.CreateOptions) (*topohubinfrastructureiov1beta1.HostOperation, error)
	Update(ctx context.Context, hostOperation *topohubinfrastructureiov1beta1.HostOperation, opts v1.UpdateOptions) (*topohubinfrastructureiov1beta1.HostOperation, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, hostOperation *topohubinfrastructureiov1beta1.HostOperation, opts v1.UpdateOptions) (*topohubinfrastructureiov1beta1.HostOperation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*topohubinfrastructureiov1beta1.HostOperation, error)
	List(ctx context.Context, opts v1.ListOptions) (*topohubinfrastructureiov1beta1.HostOperationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *topohubinfrastructureiov1beta1.HostOperation, err error)
	HostOperationExpansion
}

// hostOperations implements HostOperationInterface
type hostOperations struct {
	*gentype.ClientWithList[*topohubinfrastructureiov1beta1.HostOperation, *topohubinfrastructureiov1beta1.HostOperationList]
}

// newHostOperations returns a HostOperations
func newHostOperations(c *TopohubV1beta1Client) *hostOperations {
	return &hostOperations{
		gentype.NewClientWithList[*topohubinfrastructureiov1beta1.HostOperation, *topohubinfrastructureiov1beta1.HostOperationList](
			"hostoperations",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *topohubinfrastructureiov1beta1.HostOperation {
				return &topohubinfrastructureiov1beta1.HostOperation{}
			},
			func() *topohubinfrastructureiov1beta1.HostOperationList {
				return &topohubinfrastructureiov1beta1.HostOperationList{}
			},
		),
	}
}
