// Copyright 2024 Authors of infrastructure-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	topohubinfrastructureiov1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/apis/topohub.infrastructure.io/v1beta1"
	scheme "github.com/infrastructure-io/topohub/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RedfishStatusesGetter has a method to return a RedfishStatusInterface.
// A group's client should implement this interface.
type RedfishStatusesGetter interface {
	RedfishStatuses() RedfishStatusInterface
}

// RedfishStatusInterface has methods to work with RedfishStatus resources.
type RedfishStatusInterface interface {
	Create(ctx context.Context, redfishStatus *topohubinfrastructureiov1beta1.RedfishStatus, opts v1.CreateOptions) (*topohubinfrastructureiov1beta1.RedfishStatus, error)
	Update(ctx context.Context, redfishStatus *topohubinfrastructureiov1beta1.RedfishStatus, opts v1.UpdateOptions) (*topohubinfrastructureiov1beta1.RedfishStatus, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, redfishStatus *topohubinfrastructureiov1beta1.RedfishStatus, opts v1.UpdateOptions) (*topohubinfrastructureiov1beta1.RedfishStatus, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*topohubinfrastructureiov1beta1.RedfishStatus, error)
	List(ctx context.Context, opts v1.ListOptions) (*topohubinfrastructureiov1beta1.RedfishStatusList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *topohubinfrastructureiov1beta1.RedfishStatus, err error)
	RedfishStatusExpansion
}

// redfishStatuses implements RedfishStatusInterface
type redfishStatuses struct {
	*gentype.ClientWithList[*topohubinfrastructureiov1beta1.RedfishStatus, *topohubinfrastructureiov1beta1.RedfishStatusList]
}

// newRedfishStatuses returns a RedfishStatuses
func newRedfishStatuses(c *TopohubV1beta1Client) *redfishStatuses {
	return &redfishStatuses{
		gentype.NewClientWithList[*topohubinfrastructureiov1beta1.RedfishStatus, *topohubinfrastructureiov1beta1.RedfishStatusList](
			"redfishstatuses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *topohubinfrastructureiov1beta1.RedfishStatus {
				return &topohubinfrastructureiov1beta1.RedfishStatus{}
			},
			func() *topohubinfrastructureiov1beta1.RedfishStatusList {
				return &topohubinfrastructureiov1beta1.RedfishStatusList{}
			},
		),
	}
}
