// Copyright 2024 Authors of infrastructure-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	topohubinfrastructureiov1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/apis/topohub.infrastructure.io/v1beta1"
	scheme "github.com/infrastructure-io/topohub/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SSHStatusesGetter has a method to return a SSHStatusInterface.
// A group's client should implement this interface.
type SSHStatusesGetter interface {
	SSHStatuses() SSHStatusInterface
}

// SSHStatusInterface has methods to work with SSHStatus resources.
type SSHStatusInterface interface {
	Create(ctx context.Context, sSHStatus *topohubinfrastructureiov1beta1.SSHStatus, opts v1.CreateOptions) (*topohubinfrastructureiov1beta1.SSHStatus, error)
	Update(ctx context.Context, sSHStatus *topohubinfrastructureiov1beta1.SSHStatus, opts v1.UpdateOptions) (*topohubinfrastructureiov1beta1.SSHStatus, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, sSHStatus *topohubinfrastructureiov1beta1.SSHStatus, opts v1.UpdateOptions) (*topohubinfrastructureiov1beta1.SSHStatus, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*topohubinfrastructureiov1beta1.SSHStatus, error)
	List(ctx context.Context, opts v1.ListOptions) (*topohubinfrastructureiov1beta1.SSHStatusList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *topohubinfrastructureiov1beta1.SSHStatus, err error)
	SSHStatusExpansion
}

// sSHStatuses implements SSHStatusInterface
type sSHStatuses struct {
	*gentype.ClientWithList[*topohubinfrastructureiov1beta1.SSHStatus, *topohubinfrastructureiov1beta1.SSHStatusList]
}

// newSSHStatuses returns a SSHStatuses
func newSSHStatuses(c *TopohubV1beta1Client) *sSHStatuses {
	return &sSHStatuses{
		gentype.NewClientWithList[*topohubinfrastructureiov1beta1.SSHStatus, *topohubinfrastructureiov1beta1.SSHStatusList](
			"sshstatuses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *topohubinfrastructureiov1beta1.SSHStatus { return &topohubinfrastructureiov1beta1.SSHStatus{} },
			func() *topohubinfrastructureiov1beta1.SSHStatusList {
				return &topohubinfrastructureiov1beta1.SSHStatusList{}
			},
		),
	}
}
