// Copyright 2024 Authors of infrastructure-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	topohubinfrastructureiov1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/apis/topohub.infrastructure.io/v1beta1"
	scheme "github.com/infrastructure-io/topohub/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SubnetsGetter has a method to return a SubnetInterface.
// A group's client should implement this interface.
type SubnetsGetter interface {
	Subnets() SubnetInterface
}

// SubnetInterface has methods to work with Subnet resources.
type SubnetInterface interface {
	Create(ctx context.Context, subnet *topohubinfrastructureiov1beta1.Subnet, opts v1.CreateOptions) (*topohubinfrastructureiov1beta1.Subnet, error)
	Update(ctx context.Context, subnet *topohubinfrastructureiov1beta1.Subnet, opts v1.UpdateOptions) (*topohubinfrastructureiov1beta1.Subnet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, subnet *topohubinfrastructureiov1beta1.Subnet, opts v1.UpdateOptions) (*topohubinfrastructureiov1beta1.Subnet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*topohubinfrastructureiov1beta1.Subnet, error)
	List(ctx context.Context, opts v1.ListOptions) (*topohubinfrastructureiov1beta1.SubnetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *topohubinfrastructureiov1beta1.Subnet, err error)
	SubnetExpansion
}

// subnets implements SubnetInterface
type subnets struct {
	*gentype.ClientWithList[*topohubinfrastructureiov1beta1.Subnet, *topohubinfrastructureiov1beta1.SubnetList]
}

// newSubnets returns a Subnets
func newSubnets(c *TopohubV1beta1Client) *subnets {
	return &subnets{
		gentype.NewClientWithList[*topohubinfrastructureiov1beta1.Subnet, *topohubinfrastructureiov1beta1.SubnetList](
			"subnets",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *topohubinfrastructureiov1beta1.Subnet { return &topohubinfrastructureiov1beta1.Subnet{} },
			func() *topohubinfrastructureiov1beta1.SubnetList { return &topohubinfrastructureiov1beta1.SubnetList{} },
		),
	}
}
