// Copyright 2024 Authors of infrastructure-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	topohubinfrastructureiov1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/apis/topohub.infrastructure.io/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BindingIpLister helps list BindingIps.
// All objects returned here must be treated as read-only.
type BindingIpLister interface {
	// List lists all BindingIps in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*topohubinfrastructureiov1beta1.BindingIp, err error)
	// Get retrieves the BindingIp from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*topohubinfrastructureiov1beta1.BindingIp, error)
	BindingIpListerExpansion
}

// bindingIpLister implements the BindingIpLister interface.
type bindingIpLister struct {
	listers.ResourceIndexer[*topohubinfrastructureiov1beta1.BindingIp]
}

// NewBindingIpLister returns a new BindingIpLister.
func NewBindingIpLister(indexer cache.Indexer) BindingIpLister {
	return &bindingIpLister{listers.New[*topohubinfrastructureiov1beta1.BindingIp](indexer, topohubinfrastructureiov1beta1.Resource("bindingip"))}
}
