// Copyright 2024 Authors of infrastructure-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// BindingIpListerExpansion allows custom methods to be added to
// BindingIpLister.
type BindingIpListerExpansion interface{}

// HostEndpointListerExpansion allows custom methods to be added to
// HostEndpointLister.
type HostEndpointListerExpansion interface{}

// HostOperationListerExpansion allows custom methods to be added to
// HostOperationLister.
type HostOperationListerExpansion interface{}

// HostStatusListerExpansion allows custom methods to be added to
// HostStatusLister.
type HostStatusListerExpansion interface{}

// SubnetListerExpansion allows custom methods to be added to
// SubnetLister.
type SubnetListerExpansion interface{}
