// Copyright 2024 Authors of infrastructure-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// HostEndpointListerExpansion allows custom methods to be added to
// HostEndpointLister.
type HostEndpointListerExpansion interface{}

// HostOperationListerExpansion allows custom methods to be added to
// HostOperationLister.
type HostOperationListerExpansion interface{}

// RedfishStatusListerExpansion allows custom methods to be added to
// RedfishStatusLister.
type RedfishStatusListerExpansion interface{}

// SSHStatusListerExpansion allows custom methods to be added to
// SSHStatusLister.
type SSHStatusListerExpansion interface{}

// SubnetListerExpansion allows custom methods to be added to
// SubnetLister.
type SubnetListerExpansion interface{}
