// Copyright 2024 Authors of infrastructure-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	topohubinfrastructureiov1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/apis/topohub.infrastructure.io/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RedfishStatusLister helps list RedfishStatuses.
// All objects returned here must be treated as read-only.
type RedfishStatusLister interface {
	// List lists all RedfishStatuses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*topohubinfrastructureiov1beta1.RedfishStatus, err error)
	// Get retrieves the RedfishStatus from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*topohubinfrastructureiov1beta1.RedfishStatus, error)
	RedfishStatusListerExpansion
}

// redfishStatusLister implements the RedfishStatusLister interface.
type redfishStatusLister struct {
	listers.ResourceIndexer[*topohubinfrastructureiov1beta1.RedfishStatus]
}

// NewRedfishStatusLister returns a new RedfishStatusLister.
func NewRedfishStatusLister(indexer cache.Indexer) RedfishStatusLister {
	return &redfishStatusLister{listers.New[*topohubinfrastructureiov1beta1.RedfishStatus](indexer, topohubinfrastructureiov1beta1.Resource("redfishstatus"))}
}
