// Copyright 2024 Authors of infrastructure-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	topohubinfrastructureiov1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/apis/topohub.infrastructure.io/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SSHStatusLister helps list SSHStatuses.
// All objects returned here must be treated as read-only.
type SSHStatusLister interface {
	// List lists all SSHStatuses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*topohubinfrastructureiov1beta1.SSHStatus, err error)
	// Get retrieves the SSHStatus from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*topohubinfrastructureiov1beta1.SSHStatus, error)
	SSHStatusListerExpansion
}

// sSHStatusLister implements the SSHStatusLister interface.
type sSHStatusLister struct {
	listers.ResourceIndexer[*topohubinfrastructureiov1beta1.SSHStatus]
}

// NewSSHStatusLister returns a new SSHStatusLister.
func NewSSHStatusLister(indexer cache.Indexer) SSHStatusLister {
	return &sSHStatusLister{listers.New[*topohubinfrastructureiov1beta1.SSHStatus](indexer, topohubinfrastructureiov1beta1.Resource("sshstatus"))}
}
