// Copyright 2024 Authors of infrastructure-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	topohubinfrastructureiov1beta1 "github.com/infrastructure-io/topohub/pkg/k8s/apis/topohub.infrastructure.io/v1beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SubnetLister helps list Subnets.
// All objects returned here must be treated as read-only.
type SubnetLister interface {
	// List lists all Subnets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*topohubinfrastructureiov1beta1.Subnet, err error)
	// Get retrieves the Subnet from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*topohubinfrastructureiov1beta1.Subnet, error)
	SubnetListerExpansion
}

// subnetLister implements the SubnetLister interface.
type subnetLister struct {
	listers.ResourceIndexer[*topohubinfrastructureiov1beta1.Subnet]
}

// NewSubnetLister returns a new SubnetLister.
func NewSubnetLister(indexer cache.Indexer) SubnetLister {
	return &subnetLister{listers.New[*topohubinfrastructureiov1beta1.Subnet](indexer, topohubinfrastructureiov1beta1.Resource("subnet"))}
}
